version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_community_center
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  community-center-api:
    image: josenetop/community-center-api:latest

    container_name: community_center_api_app
    ports:
      - "7777:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data: